#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "security_review" / "threat_coverage.json"
OUTPUT = ROOT / "security_review" / "COVERAGE_MAP.md"


def _link(reference: str) -> str:
    path, separator, fragment = reference.partition("#")
    suffix = f"#{fragment}" if separator else ""
    return f"[`{reference}`](../{path}{suffix})"


def _evidence(item: dict[str, Any]) -> str:
    if item["kind"] == "suite_case":
        relation = (
            f"`{item['case_id']}` → {_link(item['fixture'])} → "
            f"**{item['expectation']}**"
        )
        if item["expectation"] == "fail":
            failures = ", ".join(
                f"`{value}`" for value in item["expected_failure_ids"]
            )
            relation += f" ({failures})"
        else:
            relation += " (positive mechanism)"
        return f"{_link(item['suite'])}: {relation}"
    tests = ", ".join(f"`{value}`" for value in item["test_ids"])
    return f"{_link(item['test_file'])}: {tests}"


def _cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def render(value: dict[str, Any]) -> str:
    threats = value["threats"]
    covered = [item for item in threats if item["status"] == "covered"]
    deferred = [item for item in threats if item["status"] == "deferred"]
    lines = [
        "# Security coverage map",
        "",
        "<!-- Generated by scripts/generate_security_coverage.py from security_review/threat_coverage.json. Do not edit by hand. -->",
        "",
        "The canonical source is [`threat_coverage.json`](threat_coverage.json). This map records repository evidence, not an independent external security review.",
        "",
        f"Current threat components: **{len(threats)}**; covered: **{len(covered)}**; deferred: **{len(deferred)}**; partial: **0**.",
        "",
        "Independent external review completed: **false**. Pairwise externally demonstrated relations: **0**.",
        "",
        "## Covered",
        "",
        "| ID | Threat component | Scope | Normative source | Executable evidence | Residual boundary |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for item in covered:
        refs = "<br>".join(_link(ref) for ref in item["normative_refs"])
        evidence = "<br>".join(_evidence(entry) for entry in item["executable_evidence"])
        lines.append(
            "| "
            + " | ".join(
                _cell(part)
                for part in (
                    f"`{item['threat_id']}`",
                    f"**{item['title']}** — {item['description']}",
                    f"`{item['scope_class']}`",
                    refs,
                    evidence,
                    item["residual_boundary"],
                )
            )
            + " |"
        )
    lines.extend(
        [
            "",
            "## Deferred",
            "",
            "Deferred means the boundary is outside a current universal protocol guarantee; it does not mean the risk is absent.",
            "",
            "| ID | Threat component | Scope | Deferral class | Boundary and rationale | Normative source |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for item in deferred:
        refs = "<br>".join(_link(ref) for ref in item["normative_refs"])
        boundary = f"{item['defer_reason']} Residual boundary: {item['residual_boundary']}"
        lines.append(
            "| "
            + " | ".join(
                _cell(part)
                for part in (
                    f"`{item['threat_id']}`",
                    f"**{item['title']}** — {item['description']}",
                    f"`{item['scope_class']}`",
                    f"`{item['defer_class']}`",
                    boundary,
                    refs,
                )
            )
            + " |"
        )
    lines.extend(
        [
            "",
            "## Interpretation boundary",
            "",
            "Covered rows establish only the protocol-observable behavior named in the row and exercised by the linked owning evidence. Deferred rows preserve deployment, local-policy, future-version, and independent-review boundaries without turning guidance or optional behavior into compatibility-rejecting rules.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    value = json.loads(SOURCE.read_text(encoding="utf-8"))
    content = render(value)
    if args.write:
        OUTPUT.write_text(content, encoding="utf-8")
        print(f"[OK] generated {OUTPUT.relative_to(ROOT).as_posix()}")
        return 0
    if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
        print("[FAIL] stale generated security_review/COVERAGE_MAP.md")
        return 1
    print("[OK] generated security coverage map is current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
